### PR TITLE
use `show_prediction_strength`

### PR DESCRIPTION
**Pull request by goolord**

### CODE REVIEW

**Comment by tzachar** [comment]
This toggle is redundant, and is a leftover from an earlier version. I think the right approach is to completely remove the toggle, and keep the current behaviour as is -- always include the details in the `data.detail` field.
It is up to the user to add the pct into the entry format anyway -- see the `format` implementation of the readme.

**Comment by goolord** [comment]
hmmm prediction strength always appears for me regardless of what `format` returns

**Comment by goolord** [comment]
image
```lua
            format = function(entry, vim_item)
                vim_item.kind = lspkind.presets.default[vim_item.kind]
                if entry.source.name == 'cmp_tabnine' then
                    vim_item.kind = ''
                end
                return vim_item
            end
```
or with format unset
image

**Comment by goolord** [comment]
unless i'm intended to overwrite `vim_item.menu`, but it seems like that complicates my configuration for what is ultimately a +3 change upstream

**Comment by goolord** [comment]
it would be even better if prediction strength was opt in imo. the prediction strength has 0 utility; it's not going to effect weather or not i (the user) am going to select that entry. it's just noise

**Comment by tzachar** [comment]
OK. I get your point.
Can you please add something regarding this in the README? Some explanation of the option is in order.
And make the option `false` by default.

**Pull request merged**
