### PR TITLE
setting `execution policy` on windows

### PR DESCRIPTION
**Pull request by xanderjakeq**

### CODE REVIEW

**Comment by tzachar** [comment]
Not windows expert, but why is this necessary? 
I had no issues installing on windows in the past. Maybe this is something specific to your setup?

**Comment by xanderjakeq** [comment]
I'm on windows 10 and I had problems installing it. I also don't use powershell much.

When I ran `powershell ./install.ps1` from the repo, I got this message.  Seems `powershell` doesn't allow running scripts by default. Might be useful for other windows users to know.
```
...\install.ps1 cannot be
loaded because running scripts is disabled on this system. For more information, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./install.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by tzachar** [comment]
Again, I think this is specific to your own setup of Windows.
Can you change the wording to something like the following:
If you get a `PSSecurityException` while trying to install, try the following in Powershell:
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`
and then give a reference to the settings.
Cool?

**Comment by tzachar** [comment]
LGTM
10x

**Pull request merged**
